### ISSUE TITLE
Unable to connect using steemconnect to all steemit apps

### ISSUE THREAD

**Issue by Priyad007** [busyorg/bsteem-public#3]
Unable to connect using steemconnect to all apps, whatever key i use. Able to login to all other account including D.tube and dsound, where steemconnect is not needed. Unable to transfer steem to buy steem power using steemconnect.
Can someone guide or cross check.
Thanks in advance

**Comment by jm90m** [comment]
Will check on this, thank you for creating this issue

**Comment by jm90m** [comment]
@Priyad007 Could you give more information on the device (android/iOS) and version you're using?
Thanks

**Comment by Priyad007** [comment]
Am using Windows 10 (64) on my laptop. Browser chrome, tried other browsers, i will now try on another laptop if system can be a issue and let you know shortly.

**Comment by Priyad007** [comment]
Doesn't work on other laptop as well.

**Comment by jm90m** [comment]
@Priyad007 This issues section is for bSteem issues. (The mobile app for android and iOS)

**Comment by Priyad007** [comment]
Am unable to connect to Busy from steemit. Can you please tell me where can i find solution for this.

**Comment by jm90m** [comment]
You can try our discord and ask there - https://discord.gg/b6344Fn

**Comment by Priyad007** [comment]
Thank you
